#!/bin/bash

export GITHUB_TOKEN=github_pat_CHANGEME
wget --quiet --wait 2 --random-wait https://download.lineageos.org/wade
awk 'BEGIN{
RS="</a>"
IGNORECASE=1
}
{
  for(o=1;o<=NF;o++){
    if ( $o ~ /href/){
      gsub(/.*href=\042/,"",$o)
      gsub(/\042.*/,"",$o)
      print $(o)
    }
  }
}' wade | grep mirrorbits | head -4 > list_of_wade

for i in `cat list_of_wade`
do
echo $i
wget --quiet --wait 2 --random-wait $i
done

find .

for i in `find . -type f \( -iname lineage\*m -o -iname lineage\*.zip -o -iname lineage\*img -iname lineage\*256 \) -printf '%f\n'`
do
echo $i
github-release upload --user alpenamilch \
   --repo backup_microg_lineageos \
   --tag wade  \
   --file $i --name $i
rm -fr $i
sleep 2
done
